import type { DecreeUploadDashboardDto } from '@/lib/api/decree-upload';
import { escapeHtml, formatPdfGeneratedTimestamp } from '@/lib/pdf/pdf-html-shared';

export type DeptReportBranding = {
  deptName: string;
  deptCode?: string;
  reportReference: string;
  /** Optional account email / label for audit trail on exported PDFs. */
  generatedBy?: string | null;
};

export type DeptReportPdfEnhancement = {
  fontFaceCss?: string;
  leftLogoDataUri?: string | null;
  rightLogoDataUri?: string | null;
};

function isoDay(d: Date = new Date()): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function csvEscape(v: unknown): string {
  if (v == null) return '';
  const s = String(v);
  if (/[,"\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function deptUploadReportBasename(prefix = 'dept-upload-report', now = new Date()): string {
  return `${prefix}-${isoDay(now)}`;
}

export function buildDeptUploadMetricsRows(
  d: DecreeUploadDashboardDto,
  branding?: DeptReportBranding | null,
): Array<{ metric: string; value: string }> {
  const dec = d.decrees ?? null;
  const other = dec?.other ?? null;
  return [
    ...(branding
      ? [
          { metric: 'departmentName', value: branding.deptName },
          ...(branding.deptCode ? [{ metric: 'departmentCode', value: branding.deptCode }] : []),
          { metric: 'reportReference', value: branding.reportReference },
          ...(branding.generatedBy ? [{ metric: 'generatedBy', value: branding.generatedBy }] : []),
        ]
      : []),
    { metric: 'generatedAt', value: String(d.generatedAt ?? '') },
    { metric: 'views_total', value: String(d.viewsTotal ?? '') },
    { metric: 'decrees_total', value: String(dec?.total ?? '') },
    { metric: 'decrees_active', value: String(dec?.active ?? '') },
    { metric: 'decrees_archived', value: String(dec?.archived ?? '') },
    { metric: 'decrees_draft', value: String(other?.draft ?? '') },
    { metric: 'decrees_superseded', value: String(other?.superseded ?? '') },
  ];
}

export function buildDeptUploadMetricsCsv(d: DecreeUploadDashboardDto, branding?: DeptReportBranding | null): string {
  const rows = buildDeptUploadMetricsRows(d, branding);
  const header = 'metric,value';
  const body = rows.map((r) => `${csvEscape(r.metric)},${csvEscape(r.value)}`).join('\n');
  return `${header}\n${body}\n`;
}

export function buildDeptUploadMetricsExcelHtml(d: DecreeUploadDashboardDto, branding?: DeptReportBranding | null): string {
  const rows = buildDeptUploadMetricsRows(d, branding);
  const tr = rows
    .map(
      (r) =>
        `<tr><td style="border:1px solid #e5e7eb;padding:8px;font-weight:700;background:#f8fafc">${escapeHtml(
          String(r.metric),
        )}</td><td style="border:1px solid #e5e7eb;padding:8px">${escapeHtml(String(r.value ?? ''))}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <table style="border-collapse:collapse;font-family:Arial, sans-serif;font-size:12px">
      <thead>
        <tr>
          <th style="border:1px solid #e5e7eb;padding:8px;text-align:left;background:#0f4c75;color:#fff">Metric</th>
          <th style="border:1px solid #e5e7eb;padding:8px;text-align:left;background:#0f4c75;color:#fff">Value</th>
        </tr>
      </thead>
      <tbody>
        ${tr}
      </tbody>
    </table>
  </body>
</html>`;
}

function metricLabel(key: string): string {
  const map: Record<string, string> = {
    departmentName: 'Department',
    departmentCode: 'Department code',
    reportReference: 'Report reference',
    generatedBy: 'Generated by',
    generatedAt: 'Dashboard snapshot time',
    views_total: 'Total views',
    decrees_total: 'Decrees (total)',
    decrees_active: 'Decrees (active)',
    decrees_archived: 'Decrees (archived)',
    decrees_draft: 'Decrees (draft)',
    decrees_superseded: 'Decrees (superseded)',
  };
  return map[key] ?? key;
}

/**
 * Enterprise analytics PDF — UTF-8, embedded Noto when provided, government-style layout with logos on every page header.
 */
export function buildDeptUploadReportPdfHtml(
  d: DecreeUploadDashboardDto,
  branding?: DeptReportBranding | null,
  enhancement?: DeptReportPdfEnhancement | null,
): string {
  const rows = buildDeptUploadMetricsRows(d, branding);
  const summaryRows = rows
    .map(
      (r, i) =>
        `<tr class="${i % 2 === 0 ? 'zebra' : ''}"><td class="mk">${escapeHtml(metricLabel(r.metric))}</td><td class="mv">${escapeHtml(
          String(r.value ?? ''),
        )}</td></tr>`,
    )
    .join('');

  const dec = d.decrees ?? null;
  const other = dec?.other ?? null;
  const eng = d.engagement;

  const kpi = [
    { k: 'Total views', v: String(d.viewsTotal ?? '—') },
    { k: 'Total downloads', v: String(eng?.totalDownloads ?? '—') },
    { k: 'Decrees', v: String(dec?.total ?? '—') },
    { k: 'Active decrees', v: String(dec?.active ?? '—') },
  ];

  const kpiHtml = kpi
    .map(
      (x) => `
    <div class="kpi">
      <div class="kpi-k">${escapeHtml(x.k)}</div>
      <div class="kpi-v">${escapeHtml(x.v)}</div>
    </div>`,
    )
    .join('');

  const topCats = (d.topCategories ?? []).slice(0, 8);
  const topCatRows = topCats
    .map(
      (c, i) =>
        `<tr class="${i % 2 === 0 ? 'zebra' : ''}"><td>${escapeHtml(c.name ?? c.namePs ?? '—')}</td><td class="num">${escapeHtml(
          String(c.decreeCount ?? ''),
        )}</td></tr>`,
    )
    .join('');

  const months = d.viewsByMonth12 ?? [];
  const maxV = Math.max(1, ...months.map((m) => m.count));
  const bars = months
    .map((m) => {
      const pct = Math.min(100, Math.round((m.count / maxV) * 100));
      return `<div class="barline"><span class="lbl">${escapeHtml(m.month)}</span><span class="bar"><i style="width:${pct}%"></i></span><span class="num">${escapeHtml(
        String(m.count),
      )}</span></div>`;
    })
    .join('');

  const recent = (d.recentUploads ?? []).slice(0, 12);
  const recentRows = recent
    .map(
      (r, i) =>
        `<tr class="${i % 2 === 0 ? 'zebra' : ''}">
      <td>${escapeHtml(r.decreeNumberLabel ?? r.decreeNumber ?? '')}</td>
      <td>${escapeHtml(r.titleSummary ?? '')}</td>
      <td class="muted">${escapeHtml(r.status ?? '')}</td>
      <td class="muted">${escapeHtml(formatPdfGeneratedTimestamp(r.publishedAt ?? r.updatedAt))}</td>
      <td class="num">${escapeHtml(String(r.viewCount ?? '—'))}</td>
    </tr>`,
    )
    .join('');

  const fontFace = enhancement?.fontFaceCss ?? '';
  const left = enhancement?.leftLogoDataUri;
  const right = enhancement?.rightLogoDataUri;
  const logoH = 44;

  const headStrip = `
<div class="pdf-head">
  <div class="pdf-head-inner">
    <div class="logo-slot">${left ? `<img class="logo" src="${left}" height="${logoH}" alt="" />` : '<span></span>'}</div>
    <div class="head-title">
      <div class="head-kicker">Department analytics — enterprise export</div>
      <div class="head-main">${branding ? escapeHtml(branding.deptName) : 'Decree upload analytics'}</div>
    </div>
    <div class="logo-slot r">${right ? `<img class="logo" src="${right}" height="${logoH}" alt="" />` : '<span></span>'}</div>
  </div>
  <div class="head-rule"></div>
</div>`;

  const coverMeta = `
<div class="cover-card">
  <div class="cover-grid">
    <div><span class="lbl-sm">Report reference</span><div class="v-lg">${escapeHtml(branding?.reportReference ?? '—')}</div></div>
    <div><span class="lbl-sm">Generated</span><div class="v-lg">${escapeHtml(formatPdfGeneratedTimestamp(d.generatedAt))}</div></div>
    <div><span class="lbl-sm">Department code</span><div class="v-lg">${escapeHtml(branding?.deptCode ?? '—')}</div></div>
    <div><span class="lbl-sm">Generated by</span><div class="v-lg">${escapeHtml(branding?.generatedBy ?? '—')}</div></div>
  </div>
</div>`;

  const wm = `<div class="wm" aria-hidden="true">CONFIDENTIAL REPORT</div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    ${fontFace}
    :root {
      --ink:#0c1829;
      --muted:#5c6b7d;
      --rule:#d7dee8;
      --band:#0f4c75;
      --paper:#fafbfd;
      --zebra:#f3f6fa;
    }
    * { box-sizing:border-box; }
    body {
      margin:0;
      padding:0;
      color:var(--ink);
      font-family:'PdfNotoNaskh','Noto Naskh Arabic','Segoe UI',Tahoma,sans-serif;
      font-size:10.5pt;
      background:var(--paper);
      line-height:1.45;
    }
    .wm {
      position:fixed;
      left:-12%; right:-12%;
      top:36%;
      text-align:center;
      font-size:46px;
      font-weight:900;
      letter-spacing:.12em;
      color:rgba(15,76,117,.06);
      transform:rotate(-28deg);
      pointer-events:none;
      z-index:0;
    }
    .shell { position:relative; z-index:1; padding:22px 22px 36px; }
    .pdf-head {
      position:fixed;
      top:0; left:0; right:0;
      z-index:2;
      background:#fff;
      padding:12px 18px 8px;
      border-bottom:1px solid var(--rule);
    }
    .pdf-head-inner {
      display:flex;
      align-items:center;
      justify-content:space-between;
      gap:12px;
      max-width:920px;
      margin:0 auto;
    }
    .logo-slot { flex:0 0 auto; min-width:72px; text-align:center; }
    .logo-slot.r { text-align:center; }
    img.logo { height:${logoH}px; width:auto; max-width:160px; object-fit:contain; image-rendering:auto; }
    .head-title { flex:1; text-align:center; }
    .head-kicker { font-size:8.5pt; letter-spacing:.09em; text-transform:uppercase; font-weight:800; color:var(--muted); }
    .head-main { font-size:13pt; font-weight:900; color:var(--band); margin-top:4px; }
    .head-rule { height:3px; margin-top:10px; background:linear-gradient(90deg,var(--band),#2d8bc7); opacity:.85; }
    .pad-header { height:104px; }
    .cover-card {
      border:1px solid var(--rule);
      border-radius:3px;
      padding:16px 18px;
      margin-bottom:18px;
      background:#fff;
    }
    .cover-grid {
      display:grid;
      grid-template-columns:1fr 1fr;
      gap:14px 18px;
    }
    .lbl-sm { font-size:8.5pt; font-weight:800; color:var(--muted); text-transform:uppercase; letter-spacing:.05em; }
    .v-lg { font-size:11pt; font-weight:800; margin-top:4px; word-break:break-word; }
    h2.section {
      font-size:10.5pt;
      letter-spacing:.08em;
      text-transform:uppercase;
      font-weight:900;
      color:var(--band);
      margin:22px 0 10px;
      padding-bottom:6px;
      border-bottom:2px solid rgba(15,76,117,.15);
      page-break-after:avoid;
    }
    .kpi-grid {
      display:grid;
      grid-template-columns:repeat(4, minmax(0,1fr));
      gap:12px;
      margin-bottom:18px;
    }
    .kpi {
      border:1px solid var(--rule);
      border-radius:3px;
      padding:12px 12px;
      background:#fff;
      page-break-inside:avoid;
    }
    .kpi-k { font-size:8.5pt; font-weight:800; color:var(--muted); text-transform:uppercase; letter-spacing:.04em; }
    .kpi-v { font-size:18pt; font-weight:900; color:var(--band); margin-top:6px; }
    table.grid {
      width:100%;
      border-collapse:collapse;
      font-size:9.5pt;
      border:1px solid var(--rule);
      background:#fff;
      page-break-inside:auto;
    }
    table.grid th {
      text-align:left;
      padding:10px 10px;
      background:#0f4c75;
      color:#fff;
      font-size:8.5pt;
      letter-spacing:.06em;
      text-transform:uppercase;
    }
    table.grid td {
      padding:9px 10px;
      border-top:1px solid var(--rule);
      vertical-align:top;
    }
    td.mk { font-weight:800; color:var(--muted); width:38%; font-size:9.5pt; }
    td.mv { font-weight:700; word-break:break-word; }
    tr.zebra td { background:var(--zebra); }
    td.num { text-align:right; font-variant-numeric:tabular-nums; }
    td.muted { color:var(--muted); font-weight:600; font-size:9pt; }
    .barline { display:flex; align-items:center; gap:8px; margin:6px 0; font-size:9pt; }
    .barline .lbl { width:72px; color:var(--muted); font-weight:700; }
    .barline .bar { flex:1; height:8px; background:#e8eef5; border-radius:99px; overflow:hidden; }
    .barline .bar i { display:block; height:100%; background:linear-gradient(90deg,#0f4c75,#3d9fd9); border-radius:99px; }
    .foot {
      margin-top:22px;
      padding-top:12px;
      border-top:1px solid var(--rule);
      font-size:8.5pt;
      color:var(--muted);
      font-weight:600;
    }
    @media print {
      .pdf-head { position:fixed; }
    }
  </style>
</head>
<body>
  ${wm}
  ${headStrip}
  <div class="pad-header"></div>
  <div class="shell">
    ${coverMeta}

    <h2 class="section">Executive snapshot</h2>
    <div class="kpi-grid">${kpiHtml}</div>

    <h2 class="section">Summary metrics</h2>
    <table class="grid" role="table">
      <thead><tr><th>Metric</th><th>Value</th></tr></thead>
      <tbody>${summaryRows}</tbody>
    </table>

    <h2 class="section">Inventory detail</h2>
    <table class="grid">
      <tbody>
        <tr class="zebra"><td class="mk">Archived</td><td class="mv num">${escapeHtml(String(dec?.archived ?? '—'))}</td></tr>
        <tr><td class="mk">Draft</td><td class="mv num">${escapeHtml(String(other?.draft ?? '—'))}</td></tr>
        <tr class="zebra"><td class="mk">Pending</td><td class="mv num">${escapeHtml(String(other?.pending ?? '—'))}</td></tr>
        <tr><td class="mk">Superseded</td><td class="mv num">${escapeHtml(String(other?.superseded ?? '—'))}</td></tr>
      </tbody>
    </table>

    <h2 class="section">Metadata completeness</h2>
    <table class="grid">
      <tbody>
        <tr class="zebra"><td>Evaluated decrees</td><td class="num">${escapeHtml(String(d.metadataCompleteness?.evaluatedDecrees ?? '—'))}</td></tr>
        <tr><td>Average score</td><td class="num">${escapeHtml(String(d.metadataCompleteness?.averageScore ?? '—'))}</td></tr>
      </tbody>
    </table>

    <h2 class="section">Top categories</h2>
    <table class="grid">
      <thead><tr><th>Category</th><th style="text-align:right">Decrees</th></tr></thead>
      <tbody>${topCatRows || `<tr><td colspan="2" class="muted">No data</td></tr>`}</tbody>
    </table>

    <h2 class="section">Views by month (12 months)</h2>
    <div class="chart">${bars || '<div class="muted">No trend data.</div>'}</div>

    <h2 class="section">Recent uploads</h2>
    <table class="grid">
      <thead>
        <tr>
          <th>Decree</th>
          <th>Title</th>
          <th>Status</th>
          <th>Published / updated</th>
          <th style="text-align:right">Views</th>
        </tr>
      </thead>
      <tbody>${recentRows || `<tr><td colspan="5" class="muted">No rows</td></tr>`}</tbody>
    </table>

    <div class="foot">
      Confidential analytics export — generated locally for offline review. Reference ${escapeHtml(
        branding?.reportReference ?? '',
      )}.
    </div>
  </div>
</body>
</html>`;
}
